import requests

facts = [
    "a veces combina las lentejas con croquetas espachurradas encima",
    "apareció en el programa de Juan y Medio disfrazado de pirata",
    "el 80% de su cuerpo está hecho de cuchillos arcos",
    "en realidad no sabe ruso",
    "es un amante de la fotografía",
    "estuvieron a punto de arrestarlo en el aeropuerto de Barcelona por intentar introducir un arma blanca en un avión",
    "estuvo una vez en Canarias",
    "fue al último concierto que ha dado y dará Hablando En Plata",
    "fue corista de Trapani en su concierto en Sevilla",
    "fue una vez al Alrumbo Fest",
    "fue uno de los primeros seguidores de @piedras.tirar",
    "gasta gran parte de su sueldo en vino",
    "ha jugado 38 minutos a team fortress 2 en Steam",
    "ha pasado la varicela",
    "ha viajado en un tren de Alta Velocidad y lo volverá a hacer",
    "inventó la pizza costrini",
    "la molienda de su café no es demasiado fina ni demasiado gruesa, y le permite extraer 30 mililitros de bebida a partir de 7 gramos de café molido, con agua a 88 °C, 9 bares de presión y en un tiempo de 25 segundos",
    "las zapatillas favoritas de Paco son las Nike TN",
    "le encanta asomarse a la azotea a vigilar el barrio",
    "le encanta hacer preguntas teóricas complejas sobre el League of Legends que implican un conocimiento profundo de las mecánicas internas del juego",
    "le encanta hacerle bromas a María, como esconderse o poner ruidos de bebé llorando en Alexa",
    "le encantan los alicuecanos",
    "le gusta pegar puñetazos a la gente",
    "no tiene ningún gato ni nunca se ha interesado por tenerlo",
    "no tuvo nada que ver con el 11-S",
    "nunca ha estado en la Antártida",
    "podría ser C.Tangana, ya que se parecen mucho y nunca se les ha visto en el mismo lugar al mismo tiempo",
    "prepara su café de importación en una cafetera De'Longhi Dedica EC685.M",
    "rompió una caja fuerte para sacar lo que había dentro y encontró la llave días después",
    "sabe ruso",
    "se desmayó en el baño del Mercado Victoria por causas que aún se desconocen",
    "su hermana y su madre se llaman Salomé",
    "su huso horario favorito es GMT+2",
    "su personaje favorito del League of Legends no es Sivir",
    "su programa de televisión favorito es Callejeros",
    "su restaurante favorito es Cocina 33",
    "tenía una colección de más de 200 botellines de cerveza",
    "tiene antepasados en Fuente Carreteros, Córdoba",
    "tiene la beta del LoL",
    "tiene más de 15.000 coronas en la App de Burger King",
    "tiene su propia página de curiosidades",
    "tiene un alias",
    "tiene un Peugeot 308 que consume unos 5L/100km",
    "tiene una bola de cristal",
    "tiene una máquina expendedora de lacasitos",
    "tiene una novia muy guapa que se llama María",
    "tiene una suscripción activa a Disney+",
    "tiene una uña del pie rara",
    "todavía no sabe utilizar Discord después de más de 4 años usándolo",
    "tuvo una tarántula",
    "a veces grita porque sí"
]

for f in facts:
	r = requests.post("https://econolistos.com:8000/facts/", json={"text": f})
	print(r.content)
	if r.status_code == 200:
		print("added: ", f)